### ISSUE TITLE
[Bug Report] Error al Deshacer un registro

### ISSUE THREAD

**Issue by jesusalbujas** [jesusalbujas/frontend-university-project#2]
#### Steps to reproduce
1. Vaya a una ventana
2. Seleccione Nuevo y llene los campos, antes de guardar de click en deshacer.
3. Cambie la vista y vera que no refresca al dar deshacer.

#### Screenshot or Gif（截图或动态图）
![error-al-deshacer](https://github.com/user-attachments/assets/c7f1375b-8550-403a-a8c8-594fbff1c694)

#### Expected behavior
Al dar click en deshacer debera limpiar los datos suministrados y al cambiar entre las vistas debera refrescar

**Comment by jesusalbujas** [comment]
## Corregido en Release
https://github.com/jesusalbujas/frontend-university-project/releases/tag/bf-1.1.7

**Comment by Zunigaj1101** [comment]
Se probó y ya no aparece el error
